// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.1
// Schema file: Sofia.Plugins.General.Contact.xsd
// Creation Date: 09/01/2007 13:36:51
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Sofia.Plugins.General.Contact
{

	public struct Declarations
	{
		public const string SchemaVersion = "";
	}




	[XmlRoot(ElementName="Document",IsNullable=false),Serializable]
	public class Document
	{

		[XmlAttribute(AttributeName="revision",DataType="integer")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __revision;
		
		[XmlIgnore]
		public string revision
		{ 
			get { return __revision; }
			set { __revision = value; }
		}

		[XmlElement(ElementName="Nom",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Nom;
		
		[XmlIgnore]
		public string Nom
		{ 
			get { return __Nom; }
			set { __Nom = value; }
		}

		[XmlElement(ElementName="Prenom",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Prenom;
		
		[XmlIgnore]
		public string Prenom
		{ 
			get { return __Prenom; }
			set { __Prenom = value; }
		}

		public Document()
		{
		}
	}
}
